version: "3.8"

services:
  heroku-postgresql:
    container_name: heroku-postgres
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
        - 5432:5432
    networks:
      - heroku-net

  heroku-quarkus:
    container_name: heroku-quarkus
    image: heroku/quarkus-jvm:1.0
    build:
      context: ./quarkus/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    networks:
      - heroku-net
    depends_on:
      - heroku-postgresql
    environment:
      - DB_ECHO_VALUES=true      
      - PORT=8080
        ### Using the DB_HEROKU_SPLIT = true  ###
      - DB_HEROKU_SPLIT=true
      - DATABASE_URL=postgres://postgres:postgres@heroku-postgresql:5432/postgres
        ### Using the DB_HEROKU_SPLIT = false ###
      # - DB_HEROKU_SPLIT=false
      # - DB_JDBC_URL=jdbc:postgresql://heroku-postgresql:5432/postgres
      # - DB_JDBC_USER=postgres
      # - DB_JDBC_PASSWORD=postgres
    
  heroku-angular:
    container_name: heroku-angular
    image: heroku/angular:1.0
    build:
      context: ./angular/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - heroku-net
    depends_on:      
      - heroku-quarkus
    environment:      
      - API_URL=http://localhost:8080
      - PORT=80

networks:
  heroku-net:
    driver: bridge
